openapi: 3.0.3
info:
  title: Jobs API
  description: API for managing user authentication and job listings
  version: 1.0.0
servers:
  - url: https://jobs-api-vui2.onrender.com/api/v1
    description: Main API server
tags:
  - name: auth
    description: Authentication-related endpoints
  - name: jobs
    description: Job management endpoints
paths:
  /auth/register:
    post:
      summary: Register a new user
      operationId: registerUser
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  example: Pengy
                email:
                  type: string
                  format: email
                  example: pengyo@gmail.com
                password:
                  type: string
                  example: secret
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                  token:
                    type: string
        '400':
          description: Invalid input
  /auth/login:
    post:
      summary: Login a user
      operationId: loginUser
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: mimo@gmail.com
                password:
                  type: string
                  example: secret
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        '401':
          description: Invalid credentials
  /jobs:
    post:
      summary: Create a new job
      operationId: createJob
      tags:
        - jobs
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - company
                - position
              properties:
                createdBy:
                  type: string
                  example: ""
                company:
                  type: string
                  example: Facebook
                position:
                  type: string
                  example: Cloud Intern
      responses:
        '201':
          description: Job created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  company:
                    type: string
                  position:
                    type: string
                  createdBy:
                    type: string
        '401':
          description: Unauthorized
    get:
      summary: Get all jobs
      operationId: getAllJobs
      tags:
        - jobs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of jobs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    company:
                      type: string
                    position:
                      type: string
                    createdBy:
                      type: string
        '401':
          description: Unauthorized
  /jobs/{id}:
    get:
      summary: Get a single job by ID
      operationId: getSingleJob
      tags:
        - jobs
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: 6825b25a1a7cccaf438b4854
      responses:
        '200':
          description: Job details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  company:
                    type: string
                  position:
                    type: string
                  createdBy:
                    type: string
        '401':
          description: Unauthorized
        '404':
          description: Job not found
    patch:
      summary: Update a job by ID
      operationId: updateJob
      tags:
        - jobs
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: 6825c3f34a515af74d4aedc1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                company:
                  type: string
                  example: Facebook
                position:
                  type: string
                  example: DevOps Junior Engineer
      responses:
        '200':
          description: Job updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  company:
                    type: string
                  position:
                    type: string
                  createdBy:
                    type: string
        '401':
          description: Unauthorized
        '404':
          description: Job not found
    delete:
      summary: Delete a job by ID
      operationId: deleteJob
      tags:
        - jobs
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: 6825c3f34a515af74d4aedc1
      responses:
        '204':
          description: Job deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Job not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT